[build]
  publish = "."

[[redirects]]
  from = "/api/prices"
  to = "/.netlify/functions/prices"
  status = 200

[[redirects]]
  from = "/api/ai"
  to = "/.netlify/functions/ai"
  status = 200

[[redirects]]
  from = "/api/ath"
  to = "/.netlify/functions/ath"
  status = 200
